application: oclock-2-56
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /style
  static_dir: style